version: '3.8'
services:
  web:
    build: .
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  redis:
    image: redis:7
    ports:
      - 6379:6379
  celery_worker:
    build: .
    command: celery -A project worker --loglevel=info
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - db
  celery_beat:
    build: .
    command: celery -A project beat --loglevel=info
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
  flower:
    build: .
    command: celery -A project flower --port=5555 --broker=${CELERY_BROKER_URL}
    ports:
      - 5555:5555
    env_file: .env
    depends_on:
      - redis
